export const FORGESTEEL_ORIGIN = 'https://forgesteel.net'
export const CURRENT_SCHEMA_VERSION = 1

export type ForgeSteelMessageType =
  | 'FORGESTEEL_READY'
  | 'FORGESTEEL_ROLL_RESULT'

export type ForgeSteelRollPayload = {
  actorName: string
  label: string
  formula: string
  total: number
  breakdown?: string
}

export type ForgeSteelBaseMessage = {
  type: ForgeSteelMessageType
  schemaVersion: 1
  messageId: string
  timestamp: string
  source: 'forgesteel'
}

export type ForgeSteelReadyMessage = ForgeSteelBaseMessage & {
  type: 'FORGESTEEL_READY'
}

export type ForgeSteelRollResultMessage = ForgeSteelBaseMessage & {
  type: 'FORGESTEEL_ROLL_RESULT'
  payload: ForgeSteelRollPayload
}

export type ForgeSteelBridgeMessage =
  | ForgeSteelReadyMessage
  | ForgeSteelRollResultMessage

export type BridgeEvent =
  | {
      kind: 'ready'
      message: ForgeSteelReadyMessage
      origin: string
    }
  | {
      kind: 'roll'
      message: ForgeSteelRollResultMessage
      origin: string
    }

export type BridgeRejectReason =
  | 'origin'
  | 'shape'
  | 'schema'
  | 'duplicate'

export type BridgeRejectEvent = {
  reason: BridgeRejectReason
  origin: string
  data: unknown
}

type BridgeOptions = {
  onEvent: (event: BridgeEvent) => void
  onReject?: (event: BridgeRejectEvent) => void
  allowedOrigins?: string[]
  allowLocalDevOrigin?: boolean
}

export function listenForForgeSteelMessages({
  onEvent,
  onReject,
  allowedOrigins = [FORGESTEEL_ORIGIN],
  allowLocalDevOrigin = import.meta.env.DEV,
}: BridgeOptions): () => void {
  const seenMessageIds = new Set<string>()

  const handleMessage = (event: MessageEvent<unknown>) => {
    const originAllowed =
      allowedOrigins.includes(event.origin) ||
      (allowLocalDevOrigin && event.origin === window.location.origin)

    if (!originAllowed) {
      onReject?.({ reason: 'origin', origin: event.origin, data: event.data })
      return
    }

    const message = parseForgeSteelMessage(event.data)

    if (!message) {
      onReject?.({ reason: 'shape', origin: event.origin, data: event.data })
      return
    }

    if (message.schemaVersion !== CURRENT_SCHEMA_VERSION) {
      onReject?.({ reason: 'schema', origin: event.origin, data: event.data })
      return
    }

    if (seenMessageIds.has(message.messageId)) {
      onReject?.({ reason: 'duplicate', origin: event.origin, data: event.data })
      return
    }

    seenMessageIds.add(message.messageId)

    if (message.type === 'FORGESTEEL_READY') {
      onEvent({ kind: 'ready', message, origin: event.origin })
      return
    }

    onEvent({ kind: 'roll', message, origin: event.origin })
  }

  window.addEventListener('message', handleMessage)

  return () => {
    window.removeEventListener('message', handleMessage)
  }
}

export function createTestRollMessage(): ForgeSteelRollResultMessage {
  return {
    type: 'FORGESTEEL_ROLL_RESULT',
    schemaVersion: CURRENT_SCHEMA_VERSION,
    messageId: crypto.randomUUID(),
    timestamp: new Date().toISOString(),
    source: 'forgesteel',
    payload: {
      actorName: 'Test Hero',
      label: 'Signature Ability',
      formula: '2d10 + 3',
      total: rollTotal(),
      breakdown: 'Generated by the extension dev harness',
    },
  }
}

export function postLocalTestRoll(): void {
  window.postMessage(createTestRollMessage(), window.location.origin)
}

function parseForgeSteelMessage(data: unknown): ForgeSteelBridgeMessage | null {
  if (!isRecord(data)) {
    return null
  }

  if (
    data.source !== 'forgesteel' ||
    typeof data.messageId !== 'string' ||
    typeof data.timestamp !== 'string' ||
    data.schemaVersion !== CURRENT_SCHEMA_VERSION
  ) {
    return null
  }

  if (data.type === 'FORGESTEEL_READY') {
    return data as ForgeSteelReadyMessage
  }

  if (data.type !== 'FORGESTEEL_ROLL_RESULT') {
    return null
  }

  if (!isRollPayload(data.payload)) {
    return null
  }

  return data as ForgeSteelRollResultMessage
}

function isRollPayload(payload: unknown): payload is ForgeSteelRollPayload {
  if (!isRecord(payload)) {
    return false
  }

  return (
    typeof payload.actorName === 'string' &&
    typeof payload.label === 'string' &&
    typeof payload.formula === 'string' &&
    typeof payload.total === 'number' &&
    Number.isFinite(payload.total) &&
    (payload.breakdown === undefined || typeof payload.breakdown === 'string')
  )
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

function rollTotal(): number {
  const first = 1 + Math.floor(Math.random() * 10)
  const second = 1 + Math.floor(Math.random() * 10)
  return first + second + 3
}
